### ISSUE TITLE
Suggestions for accessibility to visually impaired

### ISSUE THREAD

**Issue by dupreezd** [tonybird/soccermath#1]
I really like this! I'm not sure how it configures with a joystick or other mobility assistance devices but it seems like it would work well for that.

For low vision or blind users, I would suggest reading the controls at the start. "To kick press enter, to move to the right, use right arrowkey" etc. Also, I think it would be helpful to have something like "press spacebar to repeat question". I tried playing it with my eyes closed, and I would forget what the question was.

**Comment by scotthofbauer** [comment]
This is a great web app, it works very well. I also would have something in there for visually impaired players that might read out playing directions once they they hit play. But otherwise I see no other issue, thought it was a fun way to practice math skills for young students.

**Comment by tonybird** [comment]
Thanks so much for your suggestions! We've added spoken instructions and the game now repeats the question when the spacebar is pressed.
